services:
  - type: web
    name: gymshop
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn gymshop.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gymshop.settings
      - key: PYTHON_VERSION
        value: 3.10
    staticPublishPath: staticfiles