services:
  - type: web
    name: gymshop
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn gymshop.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_HOSTS
        value: gymshop-b2yx.onrender.com