# Generated by Django 5.1.6 on 2025-05-31 17:33

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=10, prefix='', primary_key=True, serialize=False),
        ),
    ]
