# Generated by Django 5.1.6 on 2025-06-12 14:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', auto_created=True, length=10, max_length=30, prefix='cart', unique=True),
        ),
    ]
