# Generated by Django 5.1.6 on 2025-06-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_city_order_country_order_county_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
