# Generated by Django 5.1.6 on 2025-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_alvailable',
            new_name='is_available',
        ),
    ]
