# Generated by Django 5.1.6 on 2025-06-16 00:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dwtlle4ic/image/upload/v1710000000/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dwtlle4ic/image/upload/v1710000000/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
